# Use root/example as user/password credentials
version: '3.1'

services:

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: kaetram_e2e
            MONGO_INITDB_ROOT_USERNAME: localroot
            MONGO_INITDB_ROOT_PASSWORD: localpass
        ports:
          [ '27017:27017' ]
        volumes:
          [ ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro ]
