blank_issues_enabled: false
contact_links:
    - name: 🤔 Questions & Discussions
      url: https://discord.gg/MmbGAaw
      about: Please ask and answer questions here.
    - name: 📃 Documentation
      url: https://github.com/Kaetram/Kaetram-Open#kaetram
      about: Please refer to it as our main documentation.
