name: Kaetram
on:
    push:
        branches: [game-content]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: development

        steps:
            - name: Deploy to the development server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEV_SERVER_HOST }}
                  username: ${{ secrets.DEV_SERVER_USERNAME }}
                  key: ${{ secrets.DEV_SERVER_KEY }}
                  port: 22
                  script: |
                      ${{ secrets.DEV_SERVER_SCRIPT }}
